### ISSUE TITLE
Incorrect Implicit Types - Push and Let directives

### ISSUE THREAD

**Issue by wSedlacek** [rx-angular/rx-angular#795] opened 2021-05-31 01:34 UTC
There seems to be some thing going on with the types the Angular Language Service is picking up for these directives.

## Push Directive

https://github.com/rx-angular/rx-angular/blob/d27cc66599819ddf3d541981cb1b29270453786d/libs/template/src/lib/push/push.pipe.ts#L112-L137

### Example
<img width="523" alt="Screen Shot 2021-05-30 at 6 23 10 PM" src="https://user-images.githubusercontent.com/8206108/120127383-1b1a2f00-c174-11eb-8d9e-46546484847c.png">
<img width="478" alt="Screen Shot 2021-05-30 at 6 22 35 PM" src="https://user-images.githubusercontent.com/8206108/120127396-21101000-c174-11eb-98eb-4ab4ae47b64e.png">
<img width="488" alt="Screen Shot 2021-05-30 at 6 22 20 PM" src="https://user-images.githubusercontent.com/8206108/120127398-21a8a680-c174-11eb-8cc8-9167a10602d5.png">

### Angular Reference

[Async Pipe](https://github.com/angular/angular/blob/037b636eb29aee5756b4d2a7d81d964da0544b1c/packages/common/src/pipes/async_pipe.ts#L102-L105)

## Let Directive

https://github.com/rx-angular/rx-angular/blob/d27cc66599819ddf3d541981cb1b29270453786d/libs/template/src/lib/let/let.directive.ts#L457-L466

### Example 
<img width="515" alt="Screen Shot 2021-05-30 at 6 28 30 PM" src="https://user-images.githubusercontent.com/8206108/120127717-f5415a00-c174-11eb-8858-111e43d2b758.png">
<img width="399" alt="Screen Shot 2021-05-30 at 6 27 40 PM" src="https://user-images.githubusercontent.com/8206108/120127757-11dd9200-c175-11eb-8877-73ad0bba2c4d.png">
<img width="423" alt="Screen Shot 2021-05-30 at 6 28 23 PM" src="https://user-images.githubusercontent.com/8206108/120127755-1144fb80-c175-11eb-8719-0db59ce27d4d.png">

### Angular Reference

[NgIfContext](https://github.com/angular/angular/blob/12.0.2/packages/common/src/directives/ng_if.ts#L241-L247)

**Comment by arturovt** [comment] 2021-05-31 22:11
Hey @wSedlacek , thanks for the issue!

Could you, please, provide a minimal reproducible example or elaborate more on the question (e.g. what version are you using)?

I've just tried to reproduce your issue with `rxLet` but I can't, see my screenshots:

![image](https://user-images.githubusercontent.com/7337691/120245397-c3fc8300-c275-11eb-8e67-57a3a5600c48.png)

![image](https://user-images.githubusercontent.com/7337691/120245427-d5de2600-c275-11eb-8536-2fde758a4efe.png)

But I was able to reproduce the `push` pipe issue, it's fixed in the current repository but the new version is not published yet :)

**Comment by wSedlacek** [comment] 2021-05-31 22:14
I'll get repo up. Thanks for looking into it!

**Comment by wSedlacek** [comment] 2021-05-31 23:02
So I have narrowed down the issue to only occurring when using the View Engine for the Angular Language Service.

## Version
```

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.0.2
Node: 14.17.0
Package Manager: pnpm 6.6.2
OS: darwin x64

Angular: 12.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.2
@angular-devkit/build-angular   12.0.2
@angular-devkit/core            12.0.2
@angular-devkit/schematics      12.0.2
@schematics/angular             12.0.2
rxjs                            6.6.7
typescript                      4.2.4
````

```
    "@rx-angular/cdk": "^1.0.0-alpha.8",
    "@rx-angular/template": "^1.0.0-beta.25",
```

## Reproduction

https://github.com/wSedlacek/rx-example

**Comment by lincolnthree** [comment] 2021-06-04 16:30
Just FYI, I believe there is currently a regression in Angular itself, even with the patched version this is not working right now:

https://github.com/angular/vscode-ng-language-service/issues/1388

**Comment by atscott** [comment] 2021-06-07 16:26
The linked issue of the language service is unrelated to types and there's no regression on types that we're aware of. It sounds like this is likely due to not having the correct compiler options enabled to get the most specific types. Can you try enabling `strictTemplates` in your `tsconfig`?

**Comment by lincolnthree** [comment] 2021-06-07 19:14
@atscott I will reply there.

**Comment by DPros** [comment] 2021-07-06 11:35
Hi, I am also having troubles with push pipe typing in 1.0.0-beta.25: the value it produces is typed as any. Is there any reason to specify the `U` parameter in class declaration `export declare class PushPipe<U> implements PipeTransform, OnDestroy {` ? Shouldn't the `transform` method be parametrized instead (e.g. `transform<U>(potentialObservable: ObservableInput<U>, config?: string | Observable<string>, renderCallback?: NextObserver<U>): U;`), just like async pipe does it?

**Comment by UrKr** [comment] 2021-07-10 18:33
> Hi, I am also having troubles with push pipe typing in 1.0.0-beta.25: the value it produces is typed as any. Is there any reason to specify the `U` parameter in class declaration `export declare class PushPipe<U> implements PipeTransform, OnDestroy {` ? Shouldn't the `transform` method be parametrized instead (e.g. `transform<U>(potentialObservable: ObservableInput<U>, config?: string | Observable<string>, renderCallback?: NextObserver<U>): U;`), just like async pipe does it?

Are you only experiencing this issue with the push pipe or rxLet also? For me it's not working with either. 
![image](https://user-images.githubusercontent.com/7669179/125173143-f3c87000-e1bd-11eb-9fe6-27d62bf12edd.png)

This has no effect. 
```
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "preserveWhitespaces": true
  }
```

**Comment by UrKr** [comment] 2021-07-10 19:39
I resolved the issue with rxLet by updating my VisualStudio code and the Angular Language Service extension... though it wasn't particularly obvious that the extension had been updated. I had to go the the extension page and press the "reload required" button.

**Comment by lincolnthree** [comment] 2021-07-12 15:05
I've also discovered that sometimes the VSCode workspace seems to get "corrupted" and the Angular Language Service stops working properly on external directives like this. I re-created the workspace with default settings and it started to work again.

**Comment by BioPhoton** [comment] 2021-08-03 23:21
So ill close this one as not a bug anymore. Feel free to reopen at any time.

**Closed by BioPhoton** 2021-08-03 23:21 UTC

**Comment by DPros** [comment] 2021-08-15 19:15
> Hi, I am also having troubles with push pipe typing in 1.0.0-beta.25: the value it produces is typed as any. Is there any reason to specify the `U` parameter in class declaration `export declare class PushPipe<U> implements PipeTransform, OnDestroy {` ? Shouldn't the `transform` method be parametrized instead (e.g. `transform<U>(potentialObservable: ObservableInput<U>, config?: string | Observable<string>, renderCallback?: NextObserver<U>): U;`), just like async pipe does it?

Hi again. I am using Intellij Idea, not VSCode, and I could not find a solution to resolve this issue from my side. I tried editing the source code of the push pipe (added `<U>` parameter to the `transform` method), and it resolves the issue.
