### ISSUE TITLE
PushPipe & RxLet do not preserve template typing for bound/piped Observables

### ISSUE THREAD

**Issue by lincolnthree** [rx-angular/rx-angular#634] opened 2021-03-30 20:58 UTC
# Description

It appears that the `push` pipe and `rxFor=` (experimental) operators do not work with Ivy template type checking. The type always breaks down to '`string`' or '`any`':

![Screen Shot 2021-03-30 at 4 50 17 PM](https://user-images.githubusercontent.com/362329/113055123-379bea00-9178-11eb-90b8-e33041b322e3.png)

angular compiler config in tsconfig.json:
```
  "angularCompilerOptions": {
    "enableIvy": true,
    "fullTemplateTypeCheck": true,
    "skipTemplateCodegen": false,
    "strictInjectionParameters": true,
    "strictMetadataEmit": true,
    "strictTemplates": true
  }
```

I would expect this to resolve the type:

![Screen Shot 2021-03-30 at 4 52 57 PM](https://user-images.githubusercontent.com/362329/113055274-6619c500-9178-11eb-81f8-72df758c0254.png)

# Steps to Reproduce the Issue

1. Use a `push` pipe on a bound `Observable<T>` and then try to reference properties of `T` in the template. They will all be of unknown type because `T` is unknown type. See screenshots above.
2. execute `ng run app:build:production`

See errors:
```
[ng]     Error occurs in the template of component TestPage.
[ng] Error: src/app/pages/test.page.html:10:40 - error TS2339: Property 'type' does not exist on type 'string'.
[ng] 10                     format="{{ payload.type }}">
[ng]                                           ~~~~        
```

# Environment

```
VSCode Angular Language Service plugin: 11.2.9 (latest at time of filing)
    "@rx-angular/cdk": "^1.0.0-alpha.7",
    "@rx-angular/state": "^1.4.3",
    "@rx-angular/template": "^1.0.0-beta.24",



Angular CLI: 12.0.0-next.5
Node: 14.15.0
OS: darwin x64

Angular: 12.0.0-next.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0-next.5
@angular-devkit/build-angular   0.1200.0-next.5
@angular-devkit/core            12.0.0-next.5
@angular-devkit/schematics      12.0.0-next.5
@angular/cdk                    12.0.0-next.4
@angular/cli                    12.0.0-next.5
@angular/fire                   6.1.4
@angular/pwa                    0.1200.0-next.5
@schematics/angular             12.0.0-next.5
@schematics/update              0.1200.0-next.5
rxjs                            6.6.7
typescript                      4.2.3
```

# Related to Other Issues

# Tasks to Resolve This

# Notes

**Comment by edbzn** [comment] 2021-04-27 15:44
I found that the `PushPipe` declaration isn't resolved by the language service, which means that the `<T>` type cannot be inferred and we get `any` as a result in the template. I don't understand why the pipe declaration is not resolved while `rxLet` gets correctly resolved.

**Comment by lincolnthree** [comment] 2021-04-27 22:25
@edbzn Yes! This is the exact same issue I am seeing. Possibly it has something to do with how the modules are exported from the library?

How are you including them in your app?

**Comment by edbzn** [comment] 2021-04-28 07:11
> Possibly it has something to do with how the modules are exported from the library?

Yes, possibly but the `LetDirective` is exported in the exact same way and it works. The problem is also visible in the demos app in the @rx-angular repository, [here for example](https://github.com/rx-angular/rx-angular/blob/master/apps/demos/src/app/features/template/pipes/push-poc/push-poc.component.ts), so I think it comes from the library itself, or maybe the new Ivy language service.

> How are you including them in your app?

Simply by importing the `PushModule` where it should.

**Comment by lincolnthree** [comment] 2021-04-28 14:44
@edbzn Interesting thanks. I actually import and re-export push pipe, so I was curious if that was common, but it sounds like it doesn't matter. 

Any thoughts from the rx-angular team on this one?

**Comment by lincolnthree** [comment] 2021-04-28 15:08
I wonder if this is related:

https://github.com/angular/angular/issues/36966

**Comment by lincolnthree** [comment] 2021-04-28 15:55
I found the issue. Apparently having a generic type on the pipe class itself causes Angular to bail out:

```
// Replacing this:
export class PushPipe<U> implements PipeTransform, OnDestroy {

// With this:
export class PushPipe<U> implements PipeTransform, OnDestroy {
```

Causes template types to resolve properly.

**Comment by lincolnthree** [comment] 2021-04-28 15:57
Here is a fully working version:

```
import { InteropObservable, Subscribable, Unsubscribable } from 'rxjs';
import { filter, switchMap, tap, withLatestFrom } from 'rxjs/operators';

import { ChangeDetectorRef, OnDestroy, Pipe, PipeTransform } from '@angular/core';
import {
  RxNotification, RxNotificationKind, RxStrategyProvider, strategyHandling, templateNotifier
} from '@rx-angular/cdk';

/**
 * @Pipe PushPipe
 *
 * @description
 *
 * The `push` pipe serves as a drop-in replacement for the `async` pipe.
 * It contains intelligent handling of change detection to enable us
 * running in zone-full as well as zone-less mode without any changes to the code.
 *
 * The current way of binding an observable to the view looks like that:
 *  ```html
 *  {{observable$ | async}}
 * <ng-container *ngIf="observable$ | async as o">{{o}}</ng-container>
 * <component [value]="observable$ | async"></component>
 * ```
 *
 * The problem is `async` pipe just marks the component and all its ancestors as dirty.
 * It needs zone.js microtask queue to exhaust until `ApplicationRef.tick` is called to render all dirty marked
 *     components.
 *
 * Heavy dynamic and interactive UIs suffer from zones change detection a lot and can
 * lean to bad performance or even unusable applications, but the `async` pipe does not work in zone-less mode.
 *
 * `push` pipe solves that problem.
 *
 * Included Features:
 *  - Take observables or promises, retrieve their values and render the value to the template
 *  - Handling null and undefined values in a clean unified/structured way
 *  - Triggers change-detection differently if `zone.js` is present or not (`detectChanges` or `markForCheck`)
 *  - Distinct same values in a row to increase performance
 *  - Coalescing of change detection calls to boost performance
 *
 * @usageNotes
 *
 * `push` pipe solves that problem. It can be used like shown here:
 * ```html
 * {{observable$ | push}}
 * <ng-container *ngIf="observable$ | push as o">{{o}}</ng-container>
 * <component [value]="observable$ | push"></component>
 * ```
 *
 * @publicApi
 */
@Pipe({ name: 'push', pure: false })
export class PushPipe implements PipeTransform, OnDestroy {
  /** @internal */
  private renderedValue: any | null | undefined;
  /** @internal */
  private readonly subscription: Unsubscribable;
  /** @internal */
  private readonly templateObserver = templateNotifier<any>();
  /** @internal */
  private readonly strategyHandler = strategyHandling(
    this.strategyProvider.primaryStrategy,
    this.strategyProvider.strategies
  );

  constructor(
    private strategyProvider: RxStrategyProvider,
    private cdRef: ChangeDetectorRef
  ) {
    const scope = (cdRef as any).context;
    this.subscription = this.templateObserver.values$
      .pipe(
        filter<RxNotification<any>>(
          (n) =>
            n.kind === RxNotificationKind.suspense ||
            n.kind === RxNotificationKind.next
        ),
        tap<RxNotification<any>>((notification) => {
          this.renderedValue = notification.value;
        }),
        withLatestFrom(this.strategyHandler.strategy$),
        switchMap(([v, strategy]) =>
          this.strategyProvider.schedule(
            () => {
              strategy.work(cdRef, scope);
            },
            {
              scope,
              strategy: strategy.name,
              patchZone: this.strategyProvider.config.patchZone ? null : false,
            }
          )
        )
      )
      .subscribe();
  }

  transform<U>(obj: Subscribable<U> | PromiseLike<U> | InteropObservable<U>): U | null;
  transform<U>(obj: null | undefined): null;
  transform<U>(obj: Subscribable<U> | PromiseLike<U> | InteropObservable<U> | null | undefined);
  transform<U>(obj: Subscribable<U> | PromiseLike<U> | InteropObservable<U> | null | undefined): U | null {
    this.templateObserver.next(obj);
    return this.renderedValue as U;
  }

  /** @internal */
  ngOnDestroy(): void {
    this.subscription.unsubscribe();
  }
}

```

**Comment by hoebbelsB** [comment] 2021-04-28 16:03
hi @lincolnthree thank u very much for investigating this.
There is a PR open for the PushPipe which tackles some of these issues: https://github.com/rx-angular/rx-angular/pull/575 it is open for quite a while now and needs new focus. 
I will check your comments and come back to you when I got more time!

**Comment by lincolnthree** [comment] 2021-04-28 16:37
@hoebbelsB No worries. I forked it for now. Thanks for looking.

**Closed** 2021-05-06 09:13 UTC
