### ISSUE TITLE
Broken template typings

### ISSUE THREAD

**Issue by hoebbelsB** [rx-angular/rx-angular#1616] opened 2023-10-13 01:38 UTC
# Description

I think [this commit](https://github.com/rx-angular/rx-angular/commit/02b62fb5da76cb3e765a35848c4961a91f96a64a) broke our template type support. Before, the types were properly inferred by whatever observable I've provided. I think it has something todo with the way how the `TemplateRef` is injected into the component. From what I know it has to be part of the constructor.

@edbzn @eneajaho any idea?

![image](https://github.com/rx-angular/rx-angular/assets/4904455/bd237e04-a92b-4cc1-b90d-d978c05e15c8)

**Comment by hoebbelsB** [comment] 2023-10-13 01:41
is it a duplicate of ? https://github.com/rx-angular/rx-angular/issues/1590

**Comment by eneajaho** [comment] 2023-10-13 07:29
![CleanShot 2023-10-13 at 09 27 54@2x](https://github.com/rx-angular/rx-angular/assets/25394362/7a6e9bd6-88a3-493d-85b3-3ea87bf4ecfe)
![CleanShot 2023-10-13 at 09 29 08@2x](https://github.com/rx-angular/rx-angular/assets/25394362/c5a482a7-1a53-4482-8e7f-5d54e335efc6)


Both vscode and webstorm infer types correctly for RxFor ?

**Comment by hoebbelsB** [comment] 2023-10-15 13:14
@eneajaho what is messing up my IDE then? :D

**Comment by eneajaho** [comment] 2023-10-15 16:05
> @eneajaho what is messing up my IDE then? :D 

Can you try in vscode to see if the issue is the IDE.

**Comment by edbzn** [comment] 2023-10-15 18:31
On my end, I never get any variable inference in the template, but it's also not working with ngFor. I compared inline HTML and separated file but same issue, not sure why. :smile:

**Comment by luii** [comment] 2023-11-01 12:19
2023.3 EAP from Webstorm got pushed out with some type inferring fixes in their changelog maybe this could fix it, i dont have any problems in webstorm though and im using `*rxFor` all the way

**Comment by hoebbelsB** [comment] 2023-11-22 23:56
hey @edbzn @eneajaho , I was curious again... so here is the result

**TemplateRef injected in ctor**
![image](https://github.com/rx-angular/rx-angular/assets/4904455/8c864a52-1df4-4837-95bd-54f84019dc45)

**TemplateRef injected with inject**
![image](https://github.com/rx-angular/rx-angular/assets/4904455/a40a3c38-afd0-481d-b022-bdc3afd031ff)


As u can see, the type is properly derived when the templateRef is injected in the ctor.... I can't explain why this happens, but it does

**Comment by eneajaho** [comment] 2023-11-23 10:14
> hey @edbzn @eneajaho , I was curious again... so here is the result
> 
> **TemplateRef injected in ctor** ![image](https://user-images.githubusercontent.com/4904455/285068003-8c864a52-1df4-4837-95bd-54f84019dc45.png)
> 
> **TemplateRef injected with inject** ![image](https://user-images.githubusercontent.com/4904455/285068105-a40a3c38-afd0-481d-b022-bdc3afd031ff.png)
> 
> As u can see, the type is properly derived when the templateRef is injected in the ctor.... I can't explain why this happens, but it does

Can you give it a try in vscode? Maybe that's an issue with Webstorm ?

**Comment by kkachniarz220** [comment] 2024-01-31 13:39
Any updates? 
![image](https://github.com/rx-angular/rx-angular/assets/50884231/971e8541-7715-4ed6-86cb-d053be30e0bb)
![image](https://github.com/rx-angular/rx-angular/assets/50884231/0e28f71d-08cb-484f-8f96-724bf1e4f6be)

**Comment by hoebbelsB** [comment] 2024-01-31 18:36
is it broken for you as well @kkachniarz220 ?

**Comment by kkachniarz220** [comment] 2024-02-01 07:23
yes

**Comment by luii** [comment] 2024-02-01 09:09
I honestly think that this is a problem with Webstorms own language service for angular, currently im on NeoVim and im using the Angular LSP with the Language-Server and Service on 17.1.0 and it shows me the correct types.

![grafik](https://github.com/rx-angular/rx-angular/assets/8077014/81cb7f5a-e90f-4ea1-82ad-17879749eb0d)

there are plenty of problems with their own integration of it if you look into their [webstorm issue tracker](https://youtrack.jetbrains.com/issues/WEB?q=angular%20template).

**Comment by luii** [comment] 2024-02-01 09:19
Maybe a upgrade to 2024 EAP would resolve your problem. If you take a look into the [changelog](https://youtrack.jetbrains.com/articles/WEB-A-233538461/WebStorm-2024.1-EAP-1-241.8102.134-build-Release-Notes) of the 2024 EAP newest update you'll find this:
![grafik](https://github.com/rx-angular/rx-angular/assets/8077014/87fb9aad-c69f-405d-ab5d-611dfa925756)

I've also checked in my 2024 EAP Version and it inferres the type correctly

**Comment by kkachniarz220** [comment] 2024-02-01 10:10
Still not working in 2024 EAP 
![image](https://github.com/rx-angular/rx-angular/assets/50884231/2272fc90-97fc-488e-8778-6bb027646a06)

**Closed** 2024-02-26 08:11 UTC
Labels: 🐞 Bug, </> Template
